Point-Of-Sales/Entities/RetailStore.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Point_Of_Sales.Entities
{
    public class RetailStore
    {
        public int Id { get; set; }
        public string RetailStoreID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        
        [JsonIgnore]
        public virtual ICollection<Employee>? Employees { get; set; }
        [ForeignKey("Invetory")]
        public int InventoryId { get; set; }
        public virtual Inventory? Inventory { get; set; }
    }
}

Point-Of-Sales/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Point_Of_Sales.Config;
using Point_Of_Sales.Entities;
using Point_Of_Sales.Models;

namespace Point_Of_Sales.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PurchasesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Purchases
        public async Task<IActionResult> Index([FromQuery] string q)
        {
            if (q != null)
            {
                var customerPurchases = await _context.PurchaseHistories.Where(p => p.Customer.Phone.Equals(q)).ToListAsync();
                return View(customerPurchases);
            }

            var id = User.FindFirst("Id")?.Value;
            if (id == null) return NotFound();

            var orders = new List<Purchase>();

            var retailId = _context.Accounts.FirstOrDefault(p => p.Id == Convert.ToInt32(id))?.Employee?.RetailStoreId;

            if (retailId != null)
            {
                orders = _context.PurchaseHistories.Where(or => or.Employee.RetailStoreId == retailId && or.Received_Money > 0).ToList();
            }

            if (User.IsInRole("Head"))
            {
                orders = _context.PurchaseHistories.ToList();

            }

            return View(orders);
        }

        // GET: Purchases/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || _context.PurchaseHistories == null)
            {
                return NotFound();
            }

            var purchase = await _context.PurchaseHistories.FirstOrDefaultAsync(m => m.purchaseId.Equals(id));

            if (purchase == null)
            {
                return NotFound();
            }

            if (purchase.Received_Money == 0)
            {
                return RedirectToAction("Checkout", new { id = purchase.purchaseId });
            }

            return View(purchase);
        }

        //public IActionResult Create()
        //{
        //    ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id");
        //    ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id");
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] PurchaseModel order)
        {
            var customer = _context.Customers.FirstOrDefault(c => c.Phone.Equals(order.Customer.Phone));


            var email = HttpContext.User.FindFirst(ClaimTypes.Email)?.Value;

            var employee = _context.Employees.FirstOrDefault(e => e.Email.Equals(email));

            if (customer == null)
            {
                customer = new Customer()
                {
                    Phone = order.Customer.Phone,
                    Name = order.Customer.Name,
                    Address = order.Customer.Address,
                };
                _context.Customers.Add(customer);
            }

            if (employee == null)
            {
                return Ok(new { Code = 1, Message = "The employee could not be found." });
            }

            var purchase = new Purchase()
            {
                Customer = customer,
                purchaseId = Guid.NewGuid().ToString(),
                Employee = employee,
                Date_Of_Purchase = DateTime.Now
            };

            foreach (var detail in order.Products)
            {
                var product = _context.Products.FirstOrDefault(p => p.Id == detail.Id);

                if (product != null && product.Is_Deleted)
                {
                    product.Is_Deleted = false;
                }

                var pdetail = new PurchaseDetail()
                {
                    Purchase = purchase,
                    Product = product,
                    Subtotal = detail.Subtotal,
                    Quantity = detail.Quantity,
                };
                // head
                //product.Quantity = product.Quantity - detail.Quantity;

                // inventory
                // var inventory = _context.Inventories.FirstOrDefault(p => p.ProductId == detail.Id);
                // inventory.Number = inventory.Number - detail.Quantity;

                purchase.Total_Amount += (double)detail.Subtotal;
                _context.PurchaseDetails.Add(pdetail);
                purchase.PurchaseDetails.Add(pdetail);
            }

            var result = await _context.SaveChangesAsync();

            if (result > 0)
            {
                return Ok(new { code = 0, returnUrl = "/Purchases/Checkout/" + purchase.purchaseId });
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Checkout(string id)
        {
            var purchase = await _context.PurchaseHistories.FirstOrDefaultAsync(p => p.purchaseId.Equals(id));
            return View(purchase);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(string id, [FromForm] double receivedMoney)
        {
            var purchase = await _context.PurchaseHistories.FirstOrDefaultAsync(p => p.purchaseId.Equals(id));

            if (purchase == null) return NotFound();

            purchase.Received_Money = receivedMoney;
            purchase.Paid_Back = receivedMoney - purchase.Total_Amount;

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = id });
        }

        // GET: Purchases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PurchaseHistories == null)
            {
                return NotFound();
            }

            var purchase = await _context.PurchaseHistories
                .Include(p => p.Customer)
                .Include(p => p.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PurchaseHistories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PurchaseHistories'  is null.");
            }
            var purchase = await _context.PurchaseHistories.FindAsync(id);
            if (purchase != null)
            {
                _context.PurchaseHistories.Remove(purchase);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PurchaseExists(int id)
        {
            return (_context.PurchaseHistories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Point-Of-Sales/Controllers/RetailStoresController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Point_Of_Sales.Config;
using Point_Of_Sales.Entities;

namespace Point_Of_Sales.Controllers
{
    public class RetailStoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RetailStoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RetailStores
        public async Task<IActionResult> Index()
        {
            return _context.RetailStores != null ?
                        View(await _context.RetailStores.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.RetailStores'  is null.");
        }

        // GET: RetailStores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.RetailStores == null)
            {
                return NotFound();
            }

            var retailStore = await _context.RetailStores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (retailStore == null)
            {
                return NotFound();
            }

            return View(retailStore);
        }

        [HttpGet]
        public async Task<IActionResult> Report([FromQuery]int q)
        {
            var id = User.FindFirst("Id")?.Value;
            if (id == null) return NotFound();

            var orders = new List<Purchase>();
            
            if (q != 0)
            {
                orders = _context.PurchaseHistories.Where(or => or.Employee.RetailStoreId == q && or.Received_Money >= or.Total_Amount).ToList();
            }
            else
            {
                var retailId = _context.Accounts.FirstOrDefault(p => p.Id == Convert.ToInt32(id))?.Employee?.RetailStoreId;
                
                if(retailId != null)
                {
                    orders = _context.PurchaseHistories.Where(or => or.Employee.RetailStoreId == retailId && or.Received_Money >= or.Total_Amount).ToList();
                }

                if (User.IsInRole("Head"))
                {
                    orders = _context.PurchaseHistories.Where(or => or.Received_Money >= or.Total_Amount).ToList();

                }
            }

            ViewBag.TotalOrder = orders.Count;

            var totalAmount = orders.Sum(or => or.Total_Amount);
            double cost = 0;

            foreach (var or in orders)
            {
                cost += or.PurchaseDetails.Sum(p => p.Product.Import_Price * p.Quantity);
            }

            ViewBag.Orders = orders ?? new List<Purchase>();
            ViewBag.TotalAmount = totalAmount;
            ViewBag.Profit = totalAmount - cost;

            return View();
        }

        // GET: RetailStores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RetailStores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RetailStoreID,Name,Address")] RetailStore retailStore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(retailStore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(retailStore);
        }

        // GET: RetailStores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.RetailStores == null)
            {
                return NotFound();
            }

            var retailStore = await _context.RetailStores.FindAsync(id);
            if (retailStore == null)
            {
                return NotFound();
            }
            return View(retailStore);
        }

        // POST: RetailStores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RetailStoreID,Name,Address")] RetailStore retailStore)
        {
            if (id != retailStore.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(retailStore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RetailStoreExists(retailStore.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(retailStore);
        }

        // GET: RetailStores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.RetailStores == null)
            {
                return NotFound();
            }

            var retailStore = await _context.RetailStores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (retailStore == null)
            {
                return NotFound();
            }

            return View(retailStore);
        }

        // POST: RetailStores/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.RetailStores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.RetailStores'  is null.");
            }
            var retailStore = await _context.RetailStores.FindAsync(id);
            if (retailStore != null)
            {
                _context.RetailStores.Remove(retailStore);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RetailStoreExists(int id)
        {
            return (_context.RetailStores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Point-Of-Sales/Views/RetailStores/Create.cshtml
@model Point_Of_Sales.Entities.RetailStore

@{
    ViewData["Title"] = "Create Retail Store";
}


<a asp-action="Index" class="btn mt-2 ml-3" style="color: #69a297"><i><u>Back to List</u></i></a>
<div class="container" style="display:flex; justify-content: center; padding-top: 4%">
    <div class="card row flex-row justify-content-around" style="width: 500px">
        <div class="row justify-content-center mt-2">
            <div class="col-md-8">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <h4 style="text-align:center; color: #55828b">Retail Store</h4>
                    <div class="form-group mt-4">
                        <label asp-for="RetailStoreID" class="control-label"></label>
                        <input asp-for="RetailStoreID" class="form-control" />
                        <span asp-validation-for="RetailStoreID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn text-white w-100" style="background-color:#55828b" />
                    </div>
                </form>
            </div>
        </div>
    </div>


</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Point-Of-Sales/Views/RetailStores/Delete.cshtml
@model Point_Of_Sales.Entities.RetailStore

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <h1>Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>RetailStore</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RetailStoreID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RetailStoreID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Point-Of-Sales/Views/RetailStores/Details.cshtml
@model Point_Of_Sales.Entities.RetailStore

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1>Details</h1>

    <div>
        <h4>RetailStore</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.RetailStoreID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.RetailStoreID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>

</div>

Point-Of-Sales/Views/RetailStores/Edit.cshtml
@model Point_Of_Sales.Entities.RetailStore

@{
    ViewData["Title"] = "Edit";
}

<div class="container">

    <h1>Edit</h1>

    <h4>RetailStore</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Edit" class="w-100 mx-0">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="RetailStoreID" class="control-label"></label>
                    <input asp-for="RetailStoreID" class="form-control" />
                    <span asp-validation-for="RetailStoreID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Point-Of-Sales/Views/RetailStores/Index.cshtml
@model IEnumerable<Point_Of_Sales.Entities.RetailStore>

@{
    ViewData["Title"] = "Retail Stores";
}

<div class="container mt-2">
    <h5 style="color: #50808e">List of Retail Stores</h5>
    <p>
        <a asp-action="Create" class="btn text-white" style="background-color: #55828b">Create New</a>
    </p>
    <table class="table text-center">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RetailStoreID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="data-@item.Id">
                    <td>
                        @Html.DisplayFor(modelItem => item.RetailStoreID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        <a href="/RetailStores/Report?q=@item.Id" class="btn text-white mr-2" style="background-color: #55828b">Report</a>
                        <button onclick="handleDelete(this)" data-id="@item.Id" class="btn text-white mr-2" style="background-color:#ad2831; ">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        async function handleDelete(button) {
            const { id } = button.dataset;

            if (confirm("Do you want to delete this retail stores?")) {
                const result = await fetch("/RetailStores/Delete/" + id, { method: "POST" })
                if (result.ok) {
                    alert("Delete successfully!");
                    document.querySelector(`#data-${id}`).remove();
                }
            } else {
                return;
            }

        }
    </script>
}

Point-Of-Sales/Views/RetailStores/Report.cshtml
@{
    ViewData["Title"] = "Report";
    var IsEmployee = User.IsInRole("Employee");
}

<div class="container">
    <div class="row mt-3 justify-content-around">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title" style="color:#3c6e71; font-weight:bold">Number of orders</h5>
                <h5 class="card-text">@(ViewBag.TotalOrder ?? 0)</h5>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title" style="color:#3c6e71; font-weight:bold">Revenue</h5>
                <h5 class="card-text">$ @(ViewBag.TotalAmount ?? 0)</h5>
            </div>
        </div>

        @if (!IsEmployee)
        {
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title" style="color:#3c6e71; font-weight:bold">Profit</h5>
                    <h5 class="card-text">$ @(ViewBag.Profit ?? 0)</h5>
                </div>
            </div>
        }
    </div>
    <div class="row mt-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        OrderId
                    </th>
                    <th>
                        Customer
                    </th>
                    <th>
                        Employee
                    </th>
                    <th>
                        Total_Amount
                    </th>
                    <th>
                        Received_Money
                    </th>
                    <th>
                        Paid_Back
                    </th>
                    <th>
                        Date_Of_Purchase
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Orders)
                {
                    <tr>
                        <td>
                            @item.purchaseId
                        </td>
                        <td>
                            @item.Customer.Name
                        </td>
                        <td>
                            @item.Employee.Fullname
                        </td>
                        <td>
                            @item.Total_Amount
                        </td>
                        <td>
                            @item.Received_Money
                        </td>
                        <td>
                            @item.Paid_Back
                        </td>
                        <td>
                            @item.Date_Of_Purchase.ToString("dd-MM-yyyy")
                        </td>
                        <td>
                            <a asp-controller="Purchases" asp-action="Details" asp-route-id="@item.purchaseId" class="btn text-black-50" style="background-color:cadetblue">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>